### ISSUE TITLE
unraid ports don't appear to take custom settings

### ISSUE THREAD

**Issue by poxin13** [binhex/arch-nginx#1]
I changed the default 8080/8443 to standard 80/443 but is not reflected in the container.

![image](https://user-images.githubusercontent.com/10375741/102556534-1adf1900-4097-11eb-8886-92083f695434.png)

![image](https://user-images.githubusercontent.com/10375741/102556541-20d4fa00-4097-11eb-94fe-ffa60d27fea4.png)

**Comment by binhex** [comment]
The reason is that you are on a custom bridge, you need to switch back to the default bridge for this to work, tested on my system:-

![image](https://user-images.githubusercontent.com/1121837/102621490-8d073a80-4137-11eb-9c7a-08d7433d6246.png)
